apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: logging
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  # This is number of nodes that we want to run
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      initContainers:
      - name: fix-permissions
        image: myFlinkContainerRegistry.azurecr.io/busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: myFlinkContainerRegistry.azurecr.io/busybox:latest
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: myFlinkContainerRegistry.azurecr.io/busybox:latest
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: myFlinkContainerRegistry.azurecr.io/elasticsearch:7.9.1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 90
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m

          # spec.template.spec.containers[elasticsearch].env
        env:
          - name: discovery.seed_hosts
            value: "elasticsearch-master.logging.svc.cluster.local"
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m

          - name: node.master
            value: "false"
          - name: node.ingest
            value: "true"
          - name: node.data
            value: "true"
          - name: cluster.remote.connect
            value: "true"
          - name: cluster.name
            value: elk-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
          - name: config
            mountPath: /usr/share/elasticsearch/jdk/lib/security/java.security
            subPath: java.security

      # spec.template.spec
      volumes:
        - name: config
          configMap:
            name: es-config

  # spec.volumeClaimTemplates
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: elk-storage-class
        resources:
          requests:
            storage: 50Gi
