apiVersion: apps/v1
kind: Deployment
metadata:
 name: camunda-filebeat-application
 namespace: dev-myind
spec:
 replicas: 1
 selector:
   matchLabels:
     app: camunda-filebeat-application
 template:
   metadata:
     labels:
       app: camunda-filebeat-application
   spec:
     containers:
     - name: beat-manual
       image: docker.elastic.co/beats/filebeat:7.5.0
       args: ["-c", "/etc/filebeat/filebeat.yaml"]
       volumeMounts:
       - name:  beat-manual-config
         mountPath: /etc/filebeat/
       - name:  manual-log-directory
         mountPath: /logs/camunda
     - name: camunda
       image: rgmyindcamunda.azurecr.io/camunda-app:latest
       imagePullPolicy: Never
       volumeMounts:
       - name: manual-log-directory
         mountPath: /logs/camunda
     volumes:
      - name: beat-manual-config
        configMap:
          name: beat-manual-config
          items:
            - key: filebeat.yaml
              path: filebeat.yaml
      - name: manual-log-directory
        emptyDir: {}